services:
  ui:
    image: ghcr.io/huggingface/chat-ui:sha-bfd6b5f
    volumes:
      - ./ui.env:/app/.env.local:ro
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

volumes:
  mongo:
